// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElCarousel: typeof import('element-plus/es')['ElCarousel']
  const ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
}
export {}
